# Generated by Django 5.0.6 on 2024-05-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qr_code_image',
            new_name='qr_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
    ]
